"""Mock MedGemma provider for local report-generation workflow demos."""

from typing import Dict, List

from ai_backend.app.ai_providers.base import AIProvider


class MockMedGemmaProvider(AIProvider):
    model_name = "mock_medgemma"

    def _split_results(self, context: Dict):
        results = context.get("results") or []
        abnormal = [item for item in results if item.get("abnormal_flag") in ("H", "L")]
        normal = [item for item in results if item.get("abnormal_flag") == "N"]
        unknown = [item for item in results if item.get("abnormal_flag") == "UNKNOWN"]
        return abnormal, normal, unknown

    def _format_results(self, results: List[Dict], limit: int = 8) -> str:
        if not results:
            return "- None identified in the available context."
        lines = []
        for item in results[:limit]:
            lines.append(
                "- {name} ({code}): {value} {unit} | flag={flag} | status={status}".format(
                    name=item.get("test_name") or "Unknown test",
                    code=item.get("loinc_code") or item.get("test_code") or "unknown",
                    value=item.get("value_raw"),
                    unit=item.get("unit") or "",
                    flag=item.get("abnormal_flag") or "UNKNOWN",
                    status=item.get("validation_status") or "UNKNOWN",
                ).strip()
            )
        if len(results) > limit:
            lines.append("- ... {} additional results not shown in this draft section.".format(len(results) - limit))
        return "\n".join(lines)

    def generate_report(self, context: Dict) -> str:
        abnormal, normal, unknown = self._split_results(context)
        return """AI Draft Biological Report

Patient ID: {patient_id}
Order ID: {order_id}
Specimen ID: {specimen_id}
Result window: {first_dt} to {last_dt}

Biological summary:
This draft summarizes {results_count} laboratory result(s) from the available GLIMS-like context. The context includes {abnormal_count} abnormal, {normal_count} normal, and {unknown_count} result(s) without rule-based classification.

Abnormal findings:
{abnormal_results}

Normal findings summary:
{normal_results}

Suggested interpretation:
The above abnormalities should be reviewed in relation to the clinical context, specimen quality, analytical method, and prior results when available. This mock provider does not establish a diagnosis and should not be used as a final medical conclusion.

Limitations:
- The source data is synthetic and pseudonymized.
- Reference-range logic is simplified for MVP demonstration.
- This report was generated by a mock MedGemma provider, not a validated medical AI model.

Biologist validation reminder:
This is an AI draft requiring review and validation by a qualified biologist before use.""".format(
            patient_id=context.get("patient_id"),
            order_id=context.get("order_id"),
            specimen_id=context.get("specimen_id"),
            first_dt=context.get("first_result_datetime"),
            last_dt=context.get("last_result_datetime"),
            results_count=context.get("results_count", 0),
            abnormal_count=context.get("abnormal_results_count", 0),
            normal_count=context.get("normal_results_count", 0),
            unknown_count=context.get("unknown_flag_results_count", 0),
            abnormal_results=self._format_results(abnormal),
            normal_results=self._format_results(normal, limit=5),
        )

    def answer_question(self, report_text: str, context: Dict, question: str) -> str:
        abnormal, normal, unknown = self._split_results(context)
        return (
            "Mock MedGemma answer based on the generated draft report and Gold context.\n\n"
            "Question: {question}\n\n"
            "Context-aware answer: This case contains {results_count} result(s), including "
            "{abnormal_count} abnormal result(s), {normal_count} normal result(s), and "
            "{unknown_count} result(s) with unknown flag status. The draft report should be "
            "used as the primary reference, and any interpretation must remain subject to "
            "biologist validation. No definitive diagnosis is provided."
        ).format(
            question=question,
            results_count=context.get("results_count", 0),
            abnormal_count=len(abnormal),
            normal_count=len(normal),
            unknown_count=len(unknown),
        )
